// Re-constructed original static constants
import { GearItem } from "./types";

export interface TutorialItem {
  id: string;
  title: string;
  author: string;
  duration: string;
  thumbnail: string;
  url: string;
}

export const FOILS: GearItem[] = [{id:"f-takoon",brand:"Takoon",name:"Takoon Pump One",image:"https://takoon.com/cdn/shop/files/Pump_2_b83406bd-06ff-4063-ad94-e8ff949ff7b4_1200x.png?v=1716589858",link:"https://takoon.com/products/foil-pump-one",price:"615€"},{id:"f-gong",brand:"Gong",name:"Gong Foil Trail V3",image:"https://www.gong-galaxy.com/cdn/shop/files/00-25-1500-FOIL-PERF_SERIES-TRAIL-GONGFOIL-TB_1.png?v=1738146721&width=1062",link:"https://www.gong-galaxy.com/products/pack-setup-pumping-trail-v3",price:"639€"},{id:"f-sroka",brand:"Sroka",name:"Sroka S-Foil High Aspect",image:"https://srokacompany.com/cdn/shop/files/8.jpg",link:"https://srokacompany.com/produit/foil-pumping-2000-ha/",price:"819€"},{id:"f-indiana-condor",brand:"Indiana",name:"Indiana Pump Foil Condor XL",image:"https://indiana-paddlesurf.com/media/catalog/product/cache/1ac056c1760bf9e921eeaadebe38cf6c/3/6/3615sq_indiana_pump_foil_condor_xl_complete_1300.png",link:"https://indiana-paddlesurf.com/en_eu/3615sq-3615sq.html",price:"1,749€"},{id:"f-alpine",brand:"Alpine",name:"Alpine Foil MODULAR ALU",image:"https://www.alpinefoil.com/medias/images/alpinefoil-modular-alu-carbone-hm-0670.jpg?v=1",link:"https://www.alpinefoil.com/kitefoil-windfoil-shop/pumping-dockstart/pumpfoil/pumpfoil-dockstart-modular-alu.html",price:"1,474€"},{id:"f-ketos",brand:"Ketos",name:"Ketos Pump winter",image:"https://www.ketos-foil.com/wp-content/uploads/2025/11/Pack-winter--scaled.png",link:"https://www.ketos-foil.com/en/pumping-packs/pack-pump-winter-ketos-carbon/",price:"1,999€"},{id:"f-afs",brand:"AFS",name:"AFS Enduro GLT",image:"https://i.imgur.com/s8o3x50.png",link:"https://afs-foiling.com/fr/produit/foil-complet-enduro-glt/",price:"2,066€"},{id:"f-axis-wakethief",brand:"Axis",name:"Wake Thief Original Edition",image:"https://axisfoils.com/cdn/shop/products/axis-foils-wake-thief-front-product-image_1296x.jpg?v=1620949745",link:"https://axisfoils.com/products/axis-foils-wake-thief-original-edition",price:"1,670€"}];

export const BOARDS: GearItem[] = [{id:"b-tools",brand:"Tools",name:"Tools Dockstart",image:"https://i.imgur.com/h6y00i0.png",link:"https://tools-surfboards.com/products/dockstart",price:"164€"},{id:"b-takoon-wood",brand:"Takoon",name:"Takoon Pump wood",image:"https://takoon.com/cdn/shop/files/Big_b8390586-9fba-4c9e-b834-542b3198ef6f_1200x.png?v=1750927502",link:"https://takoon.com/products/pump-wood-80",price:"238€"},{id:"b-gong-kluber",brand:"Gong",name:"Gong Kluber HDC",image:"https://www.gong-galaxy.com/cdn/shop/files/26-1500-PUMPING-HDC-KLUBER-BLACK-GONGPUMPING-VUE-01_c9b92044-3e56-4f30-9279-57ec374556a5.jpg?v=1772700089&width=1062",link:"https://www.gong-galaxy.com/products/gong-pump-foil-board-kluber-hdc-fiberglass",price:"359€"},{id:"b-takoon-carbon",brand:"Takoon",name:"Takoon Pump Carbon",image:"https://takoon.com/cdn/shop/files/Pocket-80-V4---Image-03_42e78c3a-85ea-4ac7-8b94-7d0b716b7dba_1200x.png?v=1750840294",link:"https://takoon.com/products/pump-carbon-80",price:"399€"},{id:"b-indiana-magic",brand:"Indiana",name:"Indiana 83 Pump Foil Magic HD",image:"https://indiana-paddlesurf.com/media/catalog/product/cache/1ac056c1760bf9e921eeaadebe38cf6c/3/2/3287sr_indiana_pump_foil_83_magic_hd.png",link:"https://indiana-paddlesurf.com/en_eu/indiana-83-pump-foil-magic-hd-3287sr.html",price:"909€"},{id:"b-sroka",brand:"Sroka",name:"Sroka Pump board",image:"https://srokacompany.com/cdn/shop/files/pump-board-V2-copie.png",link:"https://srokacompany.com/produit/pump-board-85/",price:"430€"},{id:"b-afs",brand:"AFS",name:"AFS Dock-star",image:"https://i.imgur.com/7y6gQeQ.jpeg",link:"https://afs-foiling.com/fr/produit/dock-star/",price:"739€"},{id:"b-ketos",brand:"Ketos",name:"Ketos Skull",image:"https://www.ketos-foil.com/wp-content/uploads/2025/05/SKULL-80-.png",link:"https://www.ketos-foil.com/en/pumping-en/board-dockstart-pumping-skull80/",price:"1,299€"},{id:"b-alpine",brand:"Alpine",name:"Alpine Pocket pro carbon",image:"https://www.alpinefoil.com/medias/images/pocketpump88x43.jpg?v=1",link:"https://www.alpinefoil.com/kitefoil-windfoil-shop/kitefoil-foilboard-board/pocket-pro-carbone-88-x-43.html",price:"999€"},{id:"b-diy",brand:"DIY",name:"Build your own",image:"https://i.imgur.com/DfWwHQ9.png",link:"https://www.google.com/search?q=how+to+build+your+own+pump+foil+board",price:"40€"}];

export const TUTORIALS: TutorialItem[] = [{id:"t1",title:"Best way to learn dockstart",author:"@yvonvite_AXIS",duration:"06:18",thumbnail:"https://img.youtube.com/vi/WSXoRP9TB3U/mqdefault.jpg",url:"https://www.youtube.com/watch?v=WSXoRP9TB3U"},{id:"t2",title:"How to dock start a hydrofoil",author:"@wakethief",duration:"08:13",thumbnail:"https://img.youtube.com/vi/QpjtsrMWv2U/mqdefault.jpg",url:"https://www.youtube.com/watch?v=QpjtsrMWv2U"},{id:"t3",title:"The 6 steps drill for easy dockstart",author:"@gaelfoil",duration:"12:45",thumbnail:"https://img.youtube.com/vi/hWIveY2OV-E/mqdefault.jpg",url:"https://www.youtube.com/watch?v=hWIveY2OV-E"},{id:"t4",title:"Tuto dockstart / Pumpfoil",author:"@arthurfoil",duration:"04:30",thumbnail:"https://img.youtube.com/vi/O9D2zwtnYe0/mqdefault.jpg",url:"https://www.youtube.com/watch?v=O9D2zwtnYe0"},{id:"t5",title:"How to dockstart / pumpfoil",author:"@Ludo_freefoiler",duration:"15:20",thumbnail:"https://img.youtube.com/vi/6-dSKiGtGk8/mqdefault.jpg",url:"https://www.youtube.com/watch?v=6-dSKiGtGk8"},{id:"t6",title:"How to dockstart easily",author:"@carla-surfskate",duration:"03:15",thumbnail:"https://img.youtube.com/vi/hFKKHqRgdGw/mqdefault.jpg",url:"https://www.youtube.com/watch?v=hFKKHqRgdGw"},{id:"t7",title:"HOW TO DOCKSTART - TUTO FOIL",author:"@HadrienBRUNNER",duration:"17:47",thumbnail:"https://img.youtube.com/vi/DoIGESRWpN8/mqdefault.jpg",url:"https://www.youtube.com/watch?v=DoIGESRWpN8"},{id:"t8",title:"Pump foil tutorial: how to dock start",author:"@Watersportszone",duration:"09:19",thumbnail:"https://img.youtube.com/vi/QAt2BnYpsWs/mqdefault.jpg",url:"https://www.youtube.com/watch?v=QAt2BnYpsWs"},{id:"t9",title:"3 drills to dockstart",author:"@gwen-letutour",duration:"08:18",thumbnail:"https://img.youtube.com/vi/fBYG48xN6TI/mqdefault.jpg",url:"https://www.youtube.com/watch?v=fBYG48xN6TI"}];

export const RESOURCES: GearItem[] = [{id:"r-fb",brand:"Communities",name:"Local & online communities",image:"https://i.imgur.com/elk1dK5.jpeg",link:"https://docs.google.com/spreadsheets/d/1akLjJrVY-f8TdcnA-IRXsQXrIIHKkz-Awuat4fjXFzQ/edit?usp=sharing"},{id:"r-fm",brand:"App",name:"Foilmotion Tracking",image:"https://is1-ssl.mzstatic.com/image/thumb/PurpleSource221/v4/30/4c/55/304c5573-2d93-1437-b22b-318b9db3430d/Placeholder.mill/1200x630wa.jpg",link:"https://apps.apple.com/us/app/foil-wing-surf-foilmotion/id6737276093"},{id:"r-wt",brand:"Power Pumper Club",name:"1 Minute Challenge",image:"https://static.wixstatic.com/media/2e9529_7bb0c1529bcf48738f371ebacb91487f~mv2.png/v1/fill/w_1960,h_1400,al_c,q_95,usm_0.66_1.00_0.01,enc_avif,quality_auto/Wix-3.png",link:"https://www.wakethief.com/1min-challenge"},{id:"r-wt-podcast",brand:"Podcast",name:"Up on Foil",image:"https://img.rss.com/up-on-foil/536/20251119_091107_21d6a1d282c3a6288e97ae5f7ca9413c.png",link:"https://www.uponfoil.com/"},{id:"r-physics",brand:"Physics",name:"Pump foil physics simulator",image:"https://i.imgur.com/hb9Ymq2.png",link:"https://lsegessemann.github.io/foilphysics"}];
